Add a script to find the unique git repositories via the Develocity API
gradle/develocity-build-config-samples pull request #1026
Opened 2024-01-26 14:01 UTC by runningcode

Instructions on how to use this are in the updated README.

As for performance, it is much faster than the old version.

2024-01-26 14:50 UTC, jprinet commented
> Fetching 1 days of builds from ge.solutions-team.gradle.com in batches of 1000 took
366 seconds via [the gist](https://gist.github.com/jprinet/13ffaac26a973cd20c37007e93f0a67c).
18 seconds via this script.

Impressive 👏

2024-01-26 15:06 UTC, jprinet requested changes
We need to compute differently the `FROM_INSTANT`

2024-01-26 15:36 UTC, runningcode commented on git-user-count/unique-git-repos.sh
> +FROM_INSTANT=$(date -d "$NUMBER_OF_DAYS days ago" +%s)000  # Days ago in milliseconds
Thanks for pointing this out What would be a replacement then?
I'm surprised there is no shellcheck rule for this.

2024-01-26 15:52 UTC, erichaagdev commented on git-user-count/unique-git-repos.sh
> +FROM_INSTANT=$(date -d "$NUMBER_OF_DAYS days ago" +%s)000  # Days ago in milliseconds
IMO this is something that's "standard enough" for it to be acceptable to leave it. 

For example we use it in the BVS: https://github.com/gradle/gradle-enterprise-build-validation-scripts/blob/9d5cb493bb0e035bf7494a9529217a15514dacc9/components/scripts/lib/init.sh#L18

2024-01-26 15:56 UTC, jprinet commented on git-user-count/unique-git-repos.sh
> +FROM_INSTANT=$(date -d "$NUMBER_OF_DAYS days ago" +%s)000  # Days ago in milliseconds
I had a couple of experiences where the users stumbled upon that as the initial version of my gist was using it.
I decided to switch to a server side resolution with the [advanced query syntax](https://gist.github.com/jprinet/13ffaac26a973cd20c37007e93f0a67c#file-process-scans-sh-L21)

2024-04-11 18:05 UTC, clayburn approved these changes
Made some nitpicky comments since I reviewed, but overall ok with adding this.

2024-04-11 18:05 UTC, clayburn commented on git-user-count/unique-git-repos.sh
> +        url="$url&fromBuild=$from_build"
It feels a little clunky that the query may have both `fromInstant` and `fromBuild`. If it works as intended though, it's ok I suppose.

2024-04-11 18:05 UTC, clayburn commented on git-user-count/unique-git-repos.sh
> +    if [[ num_builds -eq 0 || num_builds -lt 1000 ]]; then
Is `num_builds -eq 0` not covered by `num_builds -l 1000`?

2024-04-11 18:05 UTC, clayburn commented on git-user-count/unique-git-repos.sh
> +    echo "Usage: $0 <gradle_enterprise_url> <access_key> [number_of_days]"
It would be nice if this had arg flags like the user-count script does.

2024-04-11 18:05 UTC, clayburn commented on git-user-count/README.md
> +### Usage
We should document the `jq` dependency imo

2024-04-17 13:46 UTC, clayburn commented
@runningcode - are we ok to merge this and come back and potentially address comments later?

2024-04-17 14:15 UTC, merged